version : '3.9'

services:

  mongo:
    image: mongo:4.4.3
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/:/data/db
    ports:
      - "27017:27017"
    networks: 
      - data-network

  fastapi:
    build:
      context: ./app/python/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/code/:/app/
    ports:
      - "8000:8000"
    networks: 
        - data-network

networks:
  data-network:
    driver: bridge


